### ISSUE TITLE
hazelcast cluster in an unending stopping state

### ISSUE THREAD

**Issue by amakligo** [hazelcast/hazelcast-cloud-community#10]
this has been the state for about 2 days now. any fix?
<img width="361" alt="Screenshot 2020-10-15 at 10 16 34" src="https://user-images.githubusercontent.com/17450012/96110597-97a31a80-0ecf-11eb-91ce-8c3d4e4aadb3.png">

**Comment by huseyinbabal** [comment]
> this has been the state for about 2 days now. any fix?
> <img alt="Screenshot 2020-10-15 at 10 16 34" width="361" src="https://user-images.githubusercontent.com/17450012/96110597-97a31a80-0ecf-11eb-91ce-8c3d4e4aadb3.png">

Hi @amakligo, could you please check it now? Sorry for the inconvenience, and we are on it to find the root cause.

**Comment by amakligo** [comment]
thanks, resolved

**Comment by amakligo** [comment]
Hello @huseyinbabal please it happening again. any help please.

**Comment by huseyinbabal** [comment]
@amakligo could you please check now?

**Comment by amakligo** [comment]
![Screenshot 2021-01-18 at 11 53 33](https://user-images.githubusercontent.com/17450012/104912181-dd1a2c80-5983-11eb-9086-0ed43de69833.png)

it stopped, so I restarted it but it failed so restarted again

**Comment by amakligo** [comment]
umm Hello @huseyinbabal

**Comment by huseyinbabal** [comment]
Ok, I will get back to you for this soon

**Comment by amakligo** [comment]
thanks

**Comment by amakligo** [comment]
its running, thanks

**Comment by huseyinbabal** [comment]
@amakligo thanks for the confirmation, meanwhile we are checking this to prevent future problem.

**Comment by amakligo** [comment]
sent a linkedin request and also if you are still available for any software development pair session I am very interested. thanks

**Comment by amakligo** [comment]
![Screenshot 2022-02-05 at 17 06 54](https://user-images.githubusercontent.com/17450012/152651417-c6e5158f-d561-4e60-a4c2-89dd6366abbf.png)

Hi @huseyinbabal. me again, I'm stuck again. thanks in advance.

**Comment by amakligo** [comment]
its back up.
