### ISSUE TITLE
Hazelcast Client code is not able to connect hazelcast cloud with public IP address mentioned in IP Whitelist

### ISSUE THREAD

**Issue by prakashru** [hazelcast/hazelcast-cloud-community#3]
I have a one cluster node(free version) created in cloud.hazelcast.com. After downloading the sample code (java) and executing it from local machine (with internet connection), my code is not able to execute it when **IP Whitelist is enable** by adding my public IP address in the IP whitelist box. 

After disabling the IP Whitelist, the same client code is working fine. 

**_Please guide me, what changes I need to do in my setup for connecting hazelcast cloud using my java client code when IP whitelist is enabled._**

**The log is in below when IP whitelist enable in below:**
Jan 21, 2020 3:46:38 PM com.hazelcast.client.HazelcastClient
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] A non-empty group password is configured for the Hazelcast client. Starting with Hazelcast version 3.11, clients with the same group name, but with different group passwords (that do not use authentication) will be accepted to a cluster. The group password configuration will be removed completely in a future release.
Jan 21, 2020 3:46:39 PM com.hazelcast.client.spi.ClientInvocationService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] Running with 2 response threads, dynamic=false
Jan 21, 2020 3:46:39 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is STARTING
Jan 21, 2020 3:46:39 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is STARTED
Jan 21, 2020 3:46:39 PM com.hazelcast.client.connection.nio.ClusterConnectorService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] Trying to connect to cluster with name: hazelcast-analyticservice
Jan 21, 2020 3:46:44 PM com.hazelcast.client.spi.impl.discovery.HazelcastCloudAddressProvider
WARNING: hz.client_0 [hazelcast-analyticservice] [3.12.5] Failed to load addresses from hazelcast.cloud : java.net.SocketTimeoutException: connect timed out
Jan 21, 2020 3:46:44 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [hazelcast-analyticservice] [3.12.5] Unable to get live cluster connection, retry in 3000 ms, attempt 1 of 2.
Jan 21, 2020 3:46:49 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [hazelcast-analyticservice] [3.12.5] Unable to get live cluster connection, attempt 2 of 2.
Jan 21, 2020 3:46:49 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [hazelcast-analyticservice] [3.12.5] Unable to connect to any address for cluster: hazelcast-analyticservice. The following addresses were tried: []
Jan 21, 2020 3:46:49 PM com.hazelcast.client.connection.nio.ClusterConnectorService
WARNING: hz.client_0 [hazelcast-analyticservice] [3.12.5] Could not connect to any cluster, shutting down the client: Unable to connect to any cluster.
Jan 21, 2020 3:46:49 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is SHUTTING_DOWN
Jan 21, 2020 3:46:49 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [hazelcast-analyticservice] [3.12.5] HazelcastClient 3.12.5 (20191210 - d54936e, 294ff46) is SHUTDOWN
Exception in thread "main" java.lang.IllegalStateException: Unable to connect to any cluster.
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.connectToClusterInternal(ClusterConnectorServiceImpl.java:214)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl.access$000(ClusterConnectorServiceImpl.java:62)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:279)
	at com.hazelcast.client.connection.nio.ClusterConnectorServiceImpl$1.call(ClusterConnectorServiceImpl.java:275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)

**Comment by huseyinbabal** [comment]
@prakashru could you please provide your cluster id or name?

**Comment by prakashru** [comment]
hazelcast-analyticservice->Name of the cluster

**Comment by Frenchy** [comment]
@prakashru Hi Prakash, I am going through all the issues and doing some cleanup
have you managed to connect to your cluster using IP Whitelisting?
I will close for now but don't hesitate to contact us again if you are still running into issues

Many thanks,
Seb
