### ISSUE TITLE
I can't create cluster

### ISSUE THREAD

**Issue by tolgabeser** [hazelcast/hazelcast-cloud-community#6]
Hello,

I'm a new member.
I want to create a new cluster, but I see the error below

> Multi-Zone is not enabled for this region

I don't chose this option but i saw this error.

Thanx

**Comment by enesakar** [comment]
Hi Tolga

I just checked but could not reproduce the error. Can you please clear your browser's cache and try it again? If it happens, can you send the full screenshot so we can see all paramaters you selected.

**Comment by tolgabeser** [comment]
Hi Enes.

Resolved this problem. I was created a new cluster

Thank you for response
