### ISSUE TITLE
Cluster created resulted in a non working cluster with "failed" status

### ISSUE THREAD

**Issue by johnmdesjardins** [hazelcast/hazelcast-cloud-community#8]
Tried to create 3.12.6 cluster. Didn't work.
Then tried to delete cluster. That also didn't work.
So, now I can't create a new cluster. 
:-(
<img width="1324" alt="Screenshot 2020-06-18 15 58 01" src="https://user-images.githubusercontent.com/12104483/85066302-b6411100-b17c-11ea-9e55-ac1dc215026f.png">

**Comment by huseyinbabal** [comment]
There was a TLS certificate issue on Namecheap that caused an issue previous week, we handled it on our prod and non prod environments but didnt do that on early access environment. So, I refreshed early access env and reloaded your cluster it works.

![Screen Shot 2020-06-19 at 2 18 15 AM](https://user-images.githubusercontent.com/1237982/85101978-4ed2a200-b20c-11ea-90be-f149917195a1.png)

To save cost, I will delete it, but you can create new cluster once you need it. Let me know if you still have issue
